mvcProyectoWeb/Areas/Admin/Controllers/AlmacenesController.cs
using Microsoft.AspNetCore.Mvc;
using mvcProyectoWeb.AccesoDatos.Data.Repository.IRepository;
using mvcProyectoWeb.Models;

namespace mvcProyectoWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AlmacenesController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        public AlmacenesController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Almacen almacen)
        {
            if (ModelState.IsValid)
            {
                //logica para guardar en bd
                _contenedorTrabajo.Almacen.Add(almacen);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));

            }
            return View(almacen);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Almacen almacen = new Almacen();
            almacen = _contenedorTrabajo.Almacen.Get(id);
            if (almacen == null)
            {
                return NotFound();

            }
            return View(almacen);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Almacen almacen)
        {

            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Almacen.Update(almacen);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(almacen);
        }
        #region llamadas a la api
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Almacen.GetAll() });
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _contenedorTrabajo.Almacen.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error borrando almacen" });
            }
            _contenedorTrabajo.Almacen.Remove(objFromDb);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Se borro la almacen" });
        }
        #endregion

    }
}

mvcProyectoWeb/Areas/Admin/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using mvcProyectoWeb.Models;

namespace mvcProyectoWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

mvcProyectoWeb/Areas/Admin/Controllers/ProductosController.cs
// Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using mvcProyectoWeb.AccesoDatos.Data.Repository.IRepository;
using mvcProyectoWeb.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace mvcProyectoWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductosController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        public ProductosController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Almacenes = _contenedorTrabajo.Almacen.GetAll()
                .Select(a => new SelectListItem { Text = a.NombreAlmacen, Value = a.Id.ToString() });
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Producto producto)
        {
            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Producto.Add(producto);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Almacenes = _contenedorTrabajo.Almacen.GetAll()
                .Select(a => new SelectListItem { Text = a.NombreAlmacen, Value = a.Id.ToString() });
            return View(producto);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var producto = _contenedorTrabajo.Producto.Get(id);
            if (producto == null)
                return NotFound();

            ViewBag.Almacenes = _contenedorTrabajo.Almacen.GetAll()
                .Select(a => new SelectListItem { Text = a.NombreAlmacen, Value = a.Id.ToString() });

            return View(producto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Producto producto)
        {
            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Producto.Update(producto);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Almacenes = _contenedorTrabajo.Almacen.GetAll()
                .Select(a => new SelectListItem { Text = a.NombreAlmacen, Value = a.Id.ToString() });
            return View(producto);
        }

        #region API
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Producto.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var obj = _contenedorTrabajo.Producto.Get(id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error borrando el producto" });
            }
            _contenedorTrabajo.Producto.Remove(obj);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Producto eliminado correctamente" });
        }
        #endregion
    }
}

mvcProyectoWeb/Areas/Cliente/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using mvcProyectoWeb.Models;

namespace mvcProyectoWeb.Areas.Cliente.Controllers
{
    [Area("Cliente")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

mvcProyectoWeb/Areas/Admin/Views/Almacenes/Create.cshtml
@model mvcProyectoWeb.Models.Almacen
@{
    ViewData["Title"] = "Crear almacen";
}
<br />
<h3 class="text-center">Crear un nuevo almacen</h3>
<form method="POST" asp-action="Create">
    <div class="row px-2 offset-1 Border">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="col-10 offset-1 mt4">

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="NombreAlmacen"></label>
                </div>
                <div class="col-8">
                    <input asp-for="NombreAlmacen" class="form-control" placeholder="Ingresa el Nombre" />
                    <span asp-validation-for="NombreAlmacen" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Direccion"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Direccion" class="form-control" placeholder="Ingresa la Dirección" />
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="UrlImagen"></label>
                </div>
                <div class="col-8">
                    <input asp-for="UrlImagen" class="form-control" placeholder="URL de la imagen" />
                    <span asp-validation-for="UrlImagen" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Orden"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Orden" class="form-control" placeholder="Ingresa el orden de aparición" />
                    <span asp-validation-for="Orden" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <div class="col-8">
                    <partial name="_VistaCrearVolver" />
                </div>
            </div>

        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

mvcProyectoWeb/Areas/Admin/Views/Almacenes/Edit.cshtml
@model mvcProyectoWeb.Models.Almacen
@{
    ViewData["Title"] = "Editar almacen";
}
<h3 class="text-center">Editar almacen</h3>
<form method="POST" asp-action="Edit">
    <div class="row px-2 offset-1 Border">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="col-10 offset-1 mt4">

            <input type="hidden" asp-for="Id" />

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="NombreAlmacen"></label>
                </div>
                <div class="col-8">
                    <input asp-for="NombreAlmacen" class="form-control" placeholder="Ingresa el Nombre" />
                    <span asp-validation-for="NombreAlmacen" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Direccion"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Direccion" class="form-control" placeholder="Ingresa la Dirección" />
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="UrlImagen"></label>
                </div>
                <div class="col-8">
                    <input asp-for="UrlImagen" class="form-control" placeholder="URL de la imagen" />
                    <span asp-validation-for="UrlImagen" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Orden"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Orden" class="form-control" placeholder="Ingresa el Orden" />
                    <span asp-validation-for="Orden" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-primary form-control">Editar Almacen</button>
                </div>
                &nbsp;
                <div class="col">
                    <a asp-action="Index" class="btn btn-success form-control">Volver atrás</a>
                </div>
            </div>

        </div>
    </div>
</form>

mvcProyectoWeb/Areas/Admin/Views/Almacenes/Index.cshtml
@{
    ViewData["Title"] = "Lista de Almacenes";
}
<div class="container mt-4">
    <div class="row">
        <div class="col-8">
            <h2 class="text-primary">Lista de Almacenes</h2>
        </div>
        <div class="col-4 text-right">
            <a asp-action="Create" class="btn btn-primary">
                <i class="fa-solid fa-plus"></i>Crear Nuevo Almacen
            </a>
        </div>
    </div>
    <br />
    <br />
    <table id="tblAlmacenes" class="table table-striped table-bordered" style="width: 100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Imagen</th>
                <th>Nombre</th>
                <th>Orden</th>
                <th>Acciones</th>
            </tr>
        </thead>

    </table>

</div>

@section Scripts {
    <script src="~/js/almacen.js"></script>
}

mvcProyectoWeb/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container mt-5 text-center">
    <h1 class="text-primary fw-bold mb-4">🎓 PANEL DEL ADMINISTRADOR 🎓</h1>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <img src="https://cdn-icons-png.flaticon.com/512/3135/3135715.png" class="img-fluid mb-4" alt="Administrador" style="max-height: 200px;" />
        </div>
    </div>

    <p class="fs-5 text-dark">Bienvenido al área de administración del sistema.</p>
    <p class="text-secondary">Administrador: <strong>Juan David Uscamayta Ramos 💪</strong></p>

    <hr />

    <div class="alert alert-info mt-4">
        <strong>💡 Tip:</strong> Usa el menú superior para gestionar .
    </div>
</div>

mvcProyectoWeb/Areas/Admin/Views/Productos/Create.cshtml
@model mvcProyectoWeb.Models.Producto
@{
    ViewData["Title"] = "Crear producto";
}
<h3 class="text-center">Crear un nuevo producto</h3>

<form method="POST" asp-action="Create">
    <div class="row px-2 offset-1 border">
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="col-10 offset-1 mt-4">

            <div class="form-group row">
                <label asp-for="Nombre" class="col-4 col-form-label"></label>
                <div class="col-8">
                    <input asp-for="Nombre" class="form-control" placeholder="Ingrese el nombre" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <label asp-for="Descripcion" class="col-4 col-form-label"></label>
                <div class="col-8">
                    <textarea asp-for="Descripcion" class="form-control" rows="3" placeholder="Ingrese la descripción"></textarea>
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <label asp-for="Precio" class="col-4 col-form-label"></label>
                <div class="col-8">
                    <input asp-for="Precio" class="form-control" placeholder="Ingrese el precio" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <label asp-for="Stock" class="col-4 col-form-label"></label>
                <div class="col-8">
                    <input asp-for="Stock" class="form-control" placeholder="Ingrese el stock disponible" />
                    <span asp-validation-for="Stock" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <label asp-for="UrlImagen" class="col-4 col-form-label"></label>
                <div class="col-8">
                    <input asp-for="UrlImagen" class="form-control" placeholder="URL de la imagen" />
                    <span asp-validation-for="UrlImagen" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <label asp-for="AlmacenId" class="col-4 col-form-label"></label>
                <div class="col-8">
                    <select asp-for="AlmacenId" asp-items="ViewBag.Almacenes" class="form-control">
                        <option value="">-- Seleccione un almacén --</option>
                    </select>
                    <span asp-validation-for="AlmacenId" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <div class="col-8 offset-4">
                    <button type="submit" class="btn btn-primary form-control">
                        <i class="fa fa-plus"></i> Crear
                    </button>
                </div>
            </div>

        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

mvcProyectoWeb/Areas/Admin/Views/Productos/Edit.cshtml
@model mvcProyectoWeb.Models.Producto
@{
    ViewData["Title"] = "Editar producto";
}
<h3 class="text-center">Editar producto</h3>

<form method="POST" asp-action="Edit">
    <input type="hidden" asp-for="Id" />
    <div class="row px-2 offset-1 border">
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="col-10 offset-1 mt-4">

            <div class="form-group row">
                <label asp-for="Nombre" class="col-4 col-form-label"></label>
                <div class="col-8">
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <label asp-for="Descripcion" class="col-4 col-form-label"></label>
                <div class="col-8">
                    <textarea asp-for="Descripcion" class="form-control" rows="3"></textarea>
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <label asp-for="Precio" class="col-4 col-form-label"></label>
                <div class="col-8">
                    <input asp-for="Precio" class="form-control" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <label asp-for="Stock" class="col-4 col-form-label"></label>
                <div class="col-8">
                    <input asp-for="Stock" class="form-control" />
                    <span asp-validation-for="Stock" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <label asp-for="UrlImagen" class="col-4 col-form-label"></label>
                <div class="col-8">
                    <input asp-for="UrlImagen" class="form-control" />
                    <span asp-validation-for="UrlImagen" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <label asp-for="AlmacenId" class="col-4 col-form-label"></label>
                <div class="col-8">
                    <select asp-for="AlmacenId" asp-items="ViewBag.Almacenes" class="form-control"></select>
                    <span asp-validation-for="AlmacenId" class="text-danger"></span>
                </div>
            </div>

            <br />

            <div class="form-group row">
                <div class="col-8 offset-4">
                    <button type="submit" class="btn btn-primary form-control">
                        <i class="fa fa-save"></i> Guardar Cambios
                    </button>
                </div>
            </div>

        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

mvcProyectoWeb/Areas/Admin/Views/Productos/Index.cshtml
@{
    ViewData["Title"] = "Lista de Productos";
}
<div class="container mt-4">
    <div class="row">
        <div class="col-8">
            <h2 class="text-primary">Lista de Productos</h2>
        </div>
        <div class="col-4 text-right">
            <a asp-action="Create" class="btn btn-primary">
                <i class="fa-solid fa-plus"></i> Crear Nuevo Producto
            </a>
        </div>
    </div>
    <br />
    <br />
    <table id="tblProductos" class="table table-striped table-bordered" style="width: 100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Imagen</th>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Precio</th>
                <th>Stock</th>
                <th>Almacén</th>
                <th>Acciones</th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts {
    <script src="~/js/producto.js"></script>
}

mvcProyectoWeb/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin - mvcProyectoWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/admin.css" asp-append-version="true" />

    <!--Css todos-->
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-black border-bottom border-secondary mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-warning" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin Panel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#adminNavbar" aria-controls="adminNavbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="adminNavbar">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <!-- Enlaces internos -->
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Admin" asp-controller="Home" asp-action="Index">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" @* asp-area="Admin" asp-controller="Usuarios" asp-action="Index" *@ href="#"> Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" @* asp-area="Admin" asp-controller="Reportes"  asp-action="Index"*@ href="#">Reportes</a>
                        </li>

                        <!-- Dropdown con links externos -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Recursos externos
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" href="https://www.google.com" target="_blank">Google</a></li>
                                <li><a class="dropdown-item" href="https://github.com" target="_blank">GitHub</a></li>
                                <li><a class="dropdown-item" href="https://learn.microsoft.com" target="_blank">Docs Microsoft</a></li>
                            </ul>
                        </li>
                        <!-- Dropdown con links externos -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Almacenes
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Almacenes" asp-action="Index">Almacenes</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Almacenes" asp-action="Create">Crear Almacen</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Productos
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Productos" asp-action="Index">Productos</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Productos" asp-action="Create">Crear Producto</a></li>
                            </ul>
                        </li>
                    </ul>

                    <!-- Enlace para salir o volver al home del cliente -->
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-area="Cliente" asp-controller="Home" asp-action="Index">
                                Volver al Cliente
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top border-secondary footer text-muted mt-4">
        <div class="container">
            <span class="text-light">&copy; 2025 - Admin Panel</span>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!--Js plugins-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.0/js/dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/3.2.1/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

mvcProyectoWeb/Areas/Cliente/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

mvcProyectoWeb/Views/Shared/_VistaCrearVolver.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">
            <i class="fa fa-plus"></i> Crear
        </button>
    </div>
    &nbsp;
    <div class="col">
        <a asp-action="Index" class="btn btn-secondary form-control">
            <i class="fa fa-arrow-left"></i> Volver
        </a>
    </div>
</div>